[package]
name = "nocter-installation"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-content-integrity = { path = "../nocter-content-integrity" }
nocter-json = { path = "../nocter-json" }
nocter-model = { path = "../nocter-model" }
nocter-package = { path = "../nocter-package" }

[lints]
workspace = true
