[package]
name = "nocter-semantic-computation"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-checking = { path = "../nocter-checking" }
nocter-compile-input = { path = "../nocter-compile-input" }
nocter-computation = { path = "../nocter-computation" }
nocter-declaration-lowering = { path = "../nocter-declaration-lowering" }
nocter-discovery = { path = "../nocter-discovery" }
nocter-syntax = { path = "../nocter-syntax" }

[lints]
workspace = true
