use super::*;

#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
#[test]
fn cooperative_synchronization_crosses_native_execution() {
    let standard_root = nocter_test_support::standard_library_root();
    let package_root = TempPackage::new();
    let image = compile_single_file_native_source(
        &package_root,
        &standard_root,
        concat!(
            "use std/sync.{CancellationSource, CancellationToken, Channel, Mutex, Receive, Receiver, Send, Sender}\n",
            "use std/task\n",
            "struct Counter { value: i32 }\n",
            "async func produce(sender: Sender<i32, 2>): bool {\n",
            "    match await sender.send(1) {\n",
            "        Send.sent {}\n",
            "        Send.closed(_) { return false }\n",
            "    }\n",
            "    match await sender.send(2) {\n",
            "        Send.sent {}\n",
            "        Send.closed(_) { return false }\n",
            "    }\n",
            "    match await sender.send(3) {\n",
            "        Send.sent {}\n",
            "        Send.closed(_) { return false }\n",
            "    }\n",
            "    return true\n",
            "}\n",
            "async func consume(receiver: Receiver<i32, 2>): i32! {\n",
            "    var result: i32 = 0\n",
            "    match await receiver.receive() {\n",
            "        Receive.value(value) { result = value }\n",
            "        Receive.closed { return error.new(\"sync.closed\", \"first value was absent\") }\n",
            "    }\n",
            "    match await receiver.receive() {\n",
            "        Receive.value(value) { result = result * 10 + value }\n",
            "        Receive.closed { return error.new(\"sync.closed\", \"second value was absent\") }\n",
            "    }\n",
            "    match await receiver.receive() {\n",
            "        Receive.value(value) { result = result * 10 + value }\n",
            "        Receive.closed { return error.new(\"sync.closed\", \"third value was absent\") }\n",
            "    }\n",
            "    match await receiver.receive() {\n",
            "        Receive.value(_) { return error.new(\"sync.value\", \"closed channel produced a value\") }\n",
            "        Receive.closed { return result }\n",
            "    }\n",
            "}\n",
            "async func increment(counter: Mutex<Counter>, amount: i32): i32 {\n",
            "    var guard = await counter.lock()\n",
            "    let value: &+Counter = &+guard as &+Counter\n",
            "    value.value += amount\n",
            "    return amount\n",
            "}\n",
            "func cancelled_token(): CancellationToken! {\n",
            "    let source = CancellationSource.new()?\n",
            "    return source.token()\n",
            "}\n",
            "async func main(): i32! {\n",
            "    let channel = Channel<i32, 2>.bounded()?\n",
            "    let endpoints = channel.split()\n",
            "    let sender = move endpoints.0\n",
            "    let receiver = move endpoints.1\n",
            "    let transfer = await task.join(produce(move sender), consume(move receiver))\n",
            "    if !transfer.0 || move transfer.1? != 123 { return 1 }\n",
            "    let counter = Mutex<Counter>.new(Counter { value: 0 })?\n",
            "    let increments = await task.join(\n",
            "        increment(counter.share(), 1),\n",
            "        increment(counter.share(), 2),\n",
            "    )\n",
            "    if increments.0 + increments.1 != 3 { return 2 }\n",
            "    var guard = await counter.lock()\n",
            "    let value: &Counter = &guard as &Counter\n",
            "    if value.value != 3 { return 3 }\n",
            "    let token = cancelled_token()?\n",
            "    await token.cancelled()\n",
            "    if !token.is_cancelled() { return 4 }\n",
            "    return 0\n",
            "}\n",
        ),
    );

    execute_native_status(&image, &package_root.0, "cooperative-synchronization", 0);
}
