[package]
name = "nocter-command"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-compiler-computation = { path = "../nocter-compiler-computation" }
nocter-compile-input = { path = "../nocter-compile-input" }
nocter-diagnostics = { path = "../nocter-diagnostics" }
nocter-discovery = { path = "../nocter-discovery" }
nocter-filesystem = { path = "../nocter-filesystem" }
nocter-json = { path = "../nocter-json" }
nocter-model = { path = "../nocter-model" }
nocter-native-session = { path = "../nocter-native-session" }
nocter-package = { path = "../nocter-package" }
nocter-package-state = { path = "../nocter-package-state" }
nocter-session = { path = "../nocter-session" }
nocter-source = { path = "../nocter-source" }
nocter-source-index = { path = "../nocter-source-index" }
nocter-source-tooling = { path = "../nocter-source-tooling" }

[dev-dependencies]
nocter-syntax = { path = "../nocter-syntax" }
nocter-test-support = { path = "../nocter-test-support" }

[lints]
workspace = true
