[package]
name = "nocter-target-program"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-toolchain-contract = { path = "../nocter-toolchain-contract" }
nocter-checking = { path = "../nocter-checking" }
nocter-declarations = { path = "../nocter-declarations" }
nocter-model = { path = "../nocter-model" }
nocter-runtime-contract = { path = "../nocter-runtime-contract" }

[dev-dependencies]
nocter-checking = { path = "../nocter-checking", features = ["test-api"] }
nocter-declaration-lowering = { path = "../nocter-declaration-lowering", features = ["test-api"] }
nocter-standard-profile = { path = "../nocter-standard-profile" }
nocter-test-support = { path = "../nocter-test-support" }

[lints]
workspace = true
