[package]
name = "nocter-checking"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
test-api = []

[dependencies]
nocter-toolchain-contract = { path = "../nocter-toolchain-contract" }
nocter-compile-input = { path = "../nocter-compile-input" }
nocter-constant-evaluation = { path = "../nocter-constant-evaluation" }
nocter-declaration-lowering = { path = "../nocter-declaration-lowering" }
nocter-declarations = { path = "../nocter-declarations" }
nocter-diagnostics = { path = "../nocter-diagnostics" }
nocter-frontend-bindings = { path = "../nocter-frontend-bindings" }
nocter-model = { path = "../nocter-model" }
nocter-persistent = { path = "../nocter-persistent" }
nocter-source = { path = "../nocter-source" }
nocter-source-index = { path = "../nocter-source-index" }
nocter-syntax = { path = "../nocter-syntax" }

[dev-dependencies]
nocter-declaration-lowering = { path = "../nocter-declaration-lowering", features = ["test-api"] }

[lints]
workspace = true
