[package]
name = "nocter-workspace-analysis"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-analysis = { path = "../nocter-analysis" }
nocter-compiler-computation = { path = "../nocter-compiler-computation" }
nocter-compile-input = { path = "../nocter-compile-input" }
nocter-discovery = { path = "../nocter-discovery" }
nocter-diagnostics = { path = "../nocter-diagnostics" }
nocter-filesystem = { path = "../nocter-filesystem" }
nocter-model = { path = "../nocter-model" }
nocter-package = { path = "../nocter-package" }
nocter-session = { path = "../nocter-session" }
nocter-source = { path = "../nocter-source" }
nocter-standard-profile = { path = "../nocter-standard-profile" }
nocter-syntax = { path = "../nocter-syntax" }
nocter-workspace-revision = { path = "../nocter-workspace-revision" }

[dev-dependencies]
nocter-test-support = { path = "../nocter-test-support" }

[lints]
workspace = true
