[package]
name = "nocter-language-server"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-analysis = { path = "../nocter-analysis" }
nocter-filesystem = { path = "../nocter-filesystem" }
nocter-json = { path = "../nocter-json" }
nocter-lsp = { path = "../nocter-lsp" }

[lints]
workspace = true
