[package]
name = "nocter-package"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-filesystem = { path = "../nocter-filesystem" }
nocter-hash = { path = "../nocter-hash" }
nocter-model = { path = "../nocter-model" }
nocter-package-cache = { path = "../nocter-package-cache" }
nocter-source = { path = "../nocter-source" }
nocter-syntax = { path = "../nocter-syntax" }

[lints]
workspace = true
