[package]
name = "nocter-darwin-reactor"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-darwin-event-queue = { path = "../nocter-darwin-event-queue" }
nocter-task-runtime = { path = "../nocter-task-runtime" }

[lints]
workspace = true
