[package]
name = "nocter-arm64"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nocter-machine = { path = "../nocter-machine" }
nocter-runtime-contract = { path = "../nocter-runtime-contract" }

[dev-dependencies]
nocter-checking = { path = "../nocter-checking", features = ["test-api"] }
nocter-declaration-lowering = { path = "../nocter-declaration-lowering", features = ["test-api"] }
nocter-declarations = { path = "../nocter-declarations" }
nocter-mir = { path = "../nocter-mir" }
nocter-model = { path = "../nocter-model" }
nocter-target-program = { path = "../nocter-target-program" }
nocter-test-support = { path = "../nocter-test-support" }

[lints]
workspace = true
