[package]
name = "nocter-package-state"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nocter-model = { path = "../nocter-model" }
nocter-package = { path = "../nocter-package" }

[dev-dependencies]
nocter-filesystem = { path = "../nocter-filesystem" }
nocter-syntax = { path = "../nocter-syntax" }

[lints]
workspace = true
